config/routes.rb
Tuna::Application.routes.draw do
  resources :icons
  resources :groups_users
  resources :messages
  resources :groups
  resources :profiles
  devise_for :users
  root 'dashboard#index'

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  include AccessControl
  before_action :access_deny_before_profile_create
  before_action :authenticate_user!

  def index
    @groups = current_user.groups
  end

end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def group_link_tag(group)
    link_to group.name, "#gp#{group.id}", class: "js-group-tab",
            :data => {bind: "event: {click: change_tabs}", toggle: "tab", icon: group.icon, explain: group.explain, name: group.name, id: group.id}
  end
end

app/views/dashboard/_groups.haml
.sidebar-nav.affix(role="complementary")
  %ul.nav#group_summary
    %li.col-md-3
      = image_tag "group_icons/earth.jpg", id: 'group-icon'
    %li.col-md-9
      #group-name
    %li(style="clear:both")
    %li.col-md-12
      .form-group
        #group-explain
  %ul.nav.nav-pills.nav-stacked#group_list
    %li
      = link_to groups_path,class:"btn btn-info" do
        %span.glyphicon.glyphicon-plus-sign
          グループ参加
    - groups.each do |group|
      %li= group_link_tag group

app/views/dashboard/_message_box.haml
#message_box.row
  = form_tag messages_path, remote: true do
    = hidden_field_tag 'group_id',group_id,id:"group_id#{group_id}"
    .form-group
      = text_area nil, nil, name: "message",class: "form-control",placeholder: 'どういうことや、工藤',id:"mb#{group_id}",cols:"113",rows:"3"
    .btn-group#action-btn-area
      %button.btn.btn-default
        %span.glyphicon.glyphicon-file
        ファイル
      %button.btn.btn-default
        %span.glyphicon.glyphicon-picture
        写真
      %button.btn.btn-default
        %span.glyphicon.glyphicon-film
        動画
      %button.btn.btn-primary
        %span.glyphicon.glyphicon-pencil
        投稿

app/views/dashboard/_messages.haml
.tab-content#messages
  - groups.each do |group|
    .tab-pane.message_tab(id="gp#{group.id}")
      = render partial: 'message_box',locals: {group_id: group.id}
      .list

app/views/dashboard/index.html.haml
.container#message_list
  .col-md-3
    = render partial: 'groups',locals: {groups: @groups}

  .col-md-9.col-xs-12
    = render partial: 'messages',locals: {groups: @groups}