config/routes.rb
Tuna::Application.routes.draw do
  resources :icons
  resources :groups_users
  resources :messages
  resources :groups
  resources :profiles
  devise_for :users
  root 'dashboard#index'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  include IconCreator
  before_action :authenticate_user!
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/1/edit
  def edit
    render action: :new
  end

  # POST /profiles
  # POST /profiles.json
  def create
    icon = params["icon_img"] ?
        save_resize_icons(PROFILE_ICONS_FULL_PATH, params["icon_img"]) : ""
    @profile = Profile.new(profile_params.merge({icon: icon}))
    respond_to do |format|
      if @profile.save
        format.html { redirect_to root_path }
        format.json { render action: 'show', status: :created, location: @profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
    @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
    params.require(:profile).permit(:user_id, :name, :icon).merge(user_id: current_user.id)
  end

end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def profile_icon_img_tag
    image_tag "profile_icons/normal/#{@profile.icon.presence || 'agasa.jpg'}", id: 'icon_preview', size: "128x128"
  end
end

app/views/profiles/_form.html.haml
.container
  .col-sm-offset-4.col-sm-4
    = simple_form_for @profile ,html: {class: 'form-horizontal',multipart: true } do |f|
      - if @profile.errors.any?
        #error_explanation
          %h2= "#{pluralize(@profile.errors.count, "error")} prohibited this profile from being saved:"
          %ul
            - @profile.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.input :name, placeholder: 'あの方', input_html: {class: "form-control",maxlength: 20}

      .form-group
        = f.label :icon
        = file_field_tag 'icon_img', data: {bind: "event: {change: change_preview}"}
        = profile_icon_img_tag
      .form-group
        = f.submit '更新する',class:"btn btn-primary btn-mini"
        = link_to "戻る",root_path,class:"btn btn-default btn-mini"

app/views/profiles/edit.html.haml
%h1 Editing profile

= render 'form'

= link_to 'Show', @profile
\|
= link_to 'Back', profiles_path

app/views/profiles/index.html.haml
%h1 Listing profiles

%table
  %tr
    %th User
    %th Name
    %th Icon
    %th
    %th
    %th

  - @profiles.each do |profile|
    %tr
      %td= profile.user_id
      %td= profile.name
      %td= profile.icon
      %td= link_to 'Show', profile
      %td= link_to 'Edit', edit_profile_path(profile)
      %td= link_to 'Destroy', profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Profile', new_profile_path

app/views/profiles/new.html.haml
.container
  %blockquote.border_bottom
    %span.text-info
      プロフィール設定
= render 'form'

app/views/profiles/show.html.haml
%p#notice= notice

%p
  %b User:
  = @profile.user_id
%p
  %b Name:
  = @profile.name
%p
  %b Icon:
  = @profile.icon

= link_to 'Edit', edit_profile_path(@profile)
\|
= link_to 'Back', profiles_path