config/routes.rb
Tuna::Application.routes.draw do
  resources :icons
  resources :groups_users
  resources :messages
  resources :groups
  resources :profiles
  devise_for :users
  root 'dashboard#index'

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :messages
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include IconCreator
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @group = Group.new
    @groups = Group.all.order('created_at DESC')
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    icon = params["icon_img"] ?
        save_resize_icons(GROUP_ICONS_FULL_PATH, params["icon_img"]) : ""
    respond_to do |format|
      if current_user.groups.create group_params.merge({created_by: current_user.id, group_code: make_group_code, icon: icon})
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        #format.json { render json: @group.errors, status: :unprocessable_entity }
      end

    end

  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def group_params
    params.require(:group).permit(:name, :explain)
  end

  def make_group_code
    (("a".."z").to_a + ("A".."Z").to_a + (0..9).to_a).shuffle[0..5].join
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
  def group_icon_img_tag
    image_tag "group_icons/normal/#{@group.icon.presence || 'yjimage.jpeg'}", id: 'icon_preview', size: "128x128"
  end
end

app/views/groups/_form.html.haml
.container
  .col-sm-offset-4.col-sm-4
    = simple_form_for @group ,html: {class: 'form-horizontal',multipart: true } do |f|
      - if @group.errors.any?
        #error_explanation
          %h2= "#{pluralize(@group.errors.count, "error")} prohibited this profile from being saved:"
          %ul
            - @group.errors.full_messages.each do |msg|
              %li= msg
      .form-group
        = f.input :name, placeholder: 'ドーバー海峡', input_html: {class: "form-control",maxlength: 20}
      .form-group
        = f.label :explain
        = f.text_area :explain, id:"explain-text",class: "form-control",placeholder: '真実はいつも一つ'
      .form-group
        = f.label :icon
        = file_field_tag 'icon_img', data: {bind: "event: {change: change_preview}"}
        = group_icon_img_tag
      .form-group
        = f.submit '更新する',class:"btn btn-primary btn-mini"
        = link_to "戻る",root_path,class:"btn btn-default btn-mini"

app/views/groups/_join_group_modal.haml
#join_modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal" aria-hidden="true")
          &times;
        %h4.modal-title
          グループ参加
      = form_tag groups_users_path do
        .modal-body
          .container
            .col-sm-offset-4.col-sm-4
              .form-group
                = label_tag 'group_code',"グループコード"
                = text_field_tag 'group_code', '',class: 'form-control', placeholder: 'groupcode',maxlength: 10
        .modal-footer
          = submit_tag '閉じる',class:"btn btn-default", data: {dismiss: "modal"}
          %button.btn.btn-primary
            登録

app/views/groups/_new_group_modal.haml
#new_modal.modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close(data-dismiss="modal" aria-hidden="true")
          &times;
        %h4.modal-title
          グループ作成
      = simple_form_for @group ,html: {class: 'form-horizontal',multipart: true } do |f|
        .modal-body
          .container
            .col-sm-offset-4.col-sm-4
              .form-group
                = f.input :name, placeholder: 'ドーバー海峡', input_html: {class: "form-control",maxlength: 20}
              .form-group
                = f.label :explain
                = f.text_area :explain, id:"explain-text",class: "form-control",placeholder: '真実はいつも一つ'
              .form-group
                = f.label :icon
                = file_field_tag 'icon_img', data: {bind: "event: {change: change_preview}"}
                = group_icon_img_tag
        .modal-footer
          = f.submit '閉じる',class:"btn btn-default", data: {dismiss: "modal"}
          %button.btn.btn-primary
            登録

app/views/groups/edit.html.haml
%h1 Editing group

= render 'form'

= link_to 'Show', @group
\|
= link_to 'Back', groups_path

app/views/groups/index.html.haml
.container
  %blockquote.border_bottom
    %span.text-info
      グループ設定
  .form-group
    .btn-group
      = link_to "新しくグループを作る","#new_modal",class:"btn btn-primary", data: {toggle: "modal"}
      = link_to "グループコードを使用してグループに参加する","#join_modal",class:"btn btn-success", data: {toggle: "modal"}
  = render :partial => 'new_group_modal'
  = render :partial => 'join_group_modal'

  %table.table.table-hover
    %tr
      %th グループ名
      %th オーナー
      %th 説明
      %th
    - @groups.each do |group|
      %tr
        %td
          = image_tag  group.icon_mini
          = group.name
        %td
          = image_tag  group.owner_icon
          = group.owner_name
        %td= group.explain
        %td= link_to 'Show', group

app/views/groups/new.html.haml
%h1 New group

= render 'form'

= link_to 'Back', groups_path

app/views/groups/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @group.name
%p
  %b Icon:
  = @group.icon

= link_to 'Edit', edit_group_path(@group)
\|
= link_to 'Back', groups_path